#:kivy 1.0
#

<CalibScreen>:
    orientation: 'vertical'
    image: image

    GridLayout:
        cols: 5
        rows: 3

        # first row
        Label:
        Button:
            text: 'up'
            on_press: root.tilt += root.tilt_speed
        Label:
        Label:
        Button:
            text: 'zoom in'
            on_press: root.zoom += root.zoom_speed

        # second row
        Button:
            text: 'left'
            on_press: root.pan -= root.pan_speed
        Label:
        Button:
            text: 'right'
            on_press: root.pan += root.pan_speed
        Label:
        Label:

        # third row
        Label:
        Button:
            text: 'down'
            on_press: root.tilt -= root.tilt_speed
        Label:
        Label:
        Button:
            text: 'zoom out'
            on_press: root.zoom -= root.zoom_speed

    BoxLayout:
        Image:
            id: image
            allow_stretch: True