#:kivy 1.0
#

<CalibScreen>:
    orientation: 'vertical'
    image: image

    GridLayout:
        cols: 5
        rows: 3

        # first row
        Label:
        Button:
            text: 'up'
            on_press: root.up()
        Label:
        Label: # spacer
        Button:
            text: 'zoom in'
            on_press: root.zoom_in()

        # second row
        Button:
            text: 'left'
            on_press: root.left()
        Label:
        Button:
            text: 'right'
            on_press: root.right()
        Label:
        Label:

        # third row
        Label:
        Button:
            text: 'down'
            on_press: root.down()
        Label:
        Label: # spacer
        Button:
            text: 'zoom out'
            on_press: root.zoom_out()

    BoxLayout:
        Image:
            id: image
            source: root.filename